### ISSUE TITLE
m_b_trace function mode change

### ISSUE THREAD

**Issue by Shampjeff** [learn-co-curriculum/evaluating-regression-lines-lab#7]
The function m_b_trace has a default mode of 'line', it needs to be 'lines'

**Comment by rfaroul** [comment]
specifically, lines 10 and 23

**Comment by Socjon** [comment]
I concur with rfaroul and Shampjeff. The issue still exists.

**Comment by rhaz96** [comment]
Ditto

**Comment by rhaz96** [comment]
Same issue in the plotly lab, too

**Comment by UpwardTrajectory** [comment]
This has been going  on since Sept, still an issue in mid December ... is this a gate to intentionally figure out if candidates can de-bug code or is Flatiron School just very slow to fix stuff like this? Should I be concerned for the 15 weeks and $15,000 I'm about to invest with them?
