### ISSUE TITLE
Error using plotly

### ISSUE THREAD

**Issue by JordanTreDaniel** [learn-co-curriculum/evaluating-regression-lines-lab#9]
When entering the code for input #21, I received an error caused by the line trace's "mode" being set to "line" (no "s", somewhere in the background). I fixed it by adding a "mode" argument to the "m_b_trace" arguments and setting it equal to "lines". (with an "s")

**Comment by JordanTreDaniel** [comment]
The same issue is present with the example code when writing the function 'error'

**Comment by LoreDirick** [comment]
@JordanTreDaniel thanks for raising, fixed now!
